django-dersleri-master/accounts/urls.py
from django.urls import path
from .views import *

app_name = "accounts"

urlpatterns = [

    path('login/', login_view, name="login"),

    path('register/', register_view, name="register"),

    path('logout/', logout_view, name="logout"),

]

django-dersleri-master/blog/urls.py
from django.urls import path, include
from django.contrib import admin
from home.views import home_view
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [

    path('', home_view, name='home'),

    path('post/', include('post.urls')),

    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django-dersleri-master/post/urls.py
from django.urls import path

from .views import post_index, post_create, post_detail, post_update, post_delete

app_name = 'post'

urlpatterns = [
    path('index/', post_index, name="index"),
    path('create/', post_create, name='create'),
    path('<slug:slug>/', post_detail, name='detail'),
    path('<slug:slug>/update/', post_update, name="update"),
    path('<slug:slug>/delete/', post_delete, name='delete'),
]

django-dersleri-master/home/models.py
from django.db import models

# Create your models here.

django-dersleri-master/home/views.py
from django.shortcuts import render, HttpResponse


def home_view(request):
    if request.user.is_authenticated:
        context = {
            'isim': 'HARUN'
        }
    else:
        context = {
            'isim': 'Misafir Kullanıcı'
        }
    return render(request, 'home.html', context)

django-dersleri-master/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}Django Dersleri{% endblock %}</title>
        <!-- CSS -->
       <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  </head>
    <body>

    {% include "header.html" %}

    {% include 'messages.html' %}


    {% block body %}

    {% endblock %}


<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>

    </body>
</html>

django-dersleri-master/templates/header.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">Django Dersleri</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <form class="d-flex navbar-form mx-auto my-2 my-lg-0" method="GET" action="">
                <input class="form-control me-2" type="search" name="q" placeholder="Search on posts" value="{{ request.GET.q }}" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
            <ul class="navbar-nav ms-auto">
                {% if request.user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'post:create' %}">Yazı Ekle</a></li>
                {% endif %}
                <li class="nav-item"><a class="nav-link" href="{% url 'home' %}">Anasayfa</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'post:index' %}">Blog</a></li>
                <li class="nav-item"><a class="nav-link" href="#">Hakkımda</a></li>
                <li class="nav-item"><a class="nav-link" href="#">İletişim</a></li>
                {% if not request.user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'accounts:register' %}">Üye Ol</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'accounts:login' %}">Giriş</a></li>
                {% else %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'accounts:logout' %}">Çıkış</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

django-dersleri-master/templates/home.html
{% extends 'base.html' %}

{% block title %}
    Anasayfa - {{ block.super }}
{% endblock %}

{% block body %}
    <div class="container-fluid">
{#        <div class="row" style="margin-bottom: 30px;">#}
{#            <div class="col-md-3 col-sm-6" style="background-color: #ff0000; height: 100px;">1. Ürün</div>#}
{#            <div class="col-md-3 col-sm-6" style="background-color: #ffca11; height: 100px;">2. Ürün</div>#}
{#            <div class="col-md-3 col-sm-6" style="background-color: #56ff25; height: 100px;">3. Ürün</div>#}
{#            <div class="col-md-3 col-sm-6" style="background-color: #244cff; height: 100px;">4. Ürün</div>#}
{#        </div>#}
{##}
{#        <div class="row" style="margin-bottom: 30px;">#}
{#            <div class="col-md-3 col-sm-6" style="background-color: #ff0000; height: 100px;">1. Ürün</div>#}
{#            <div class="col-md-3 col-sm-6" style="background-color: #ffca11; height: 100px;">2. Ürün</div>#}
{#            <div class="col-md-3 col-sm-6" style="background-color: #56ff25; height: 100px;">3. Ürün</div>#}
{#            <div class="col-md-3 col-sm-6" style="background-color: #244cff; height: 100px;">4. Ürün</div>#}
{#        </div>#}
{##}
{#        <div class="row" style="margin-bottom: 30px;">#}
{#            <div class="col-md-3 col-sm-6" style="background-color: #ff0000; height: 100px;">1. Ürün</div>#}
{#            <div class="col-md-3 col-sm-6" style="background-color: #ffca11; height: 100px;">2. Ürün</div>#}
{#            <div class="col-md-3 col-sm-6" style="background-color: #56ff25; height: 100px;">3. Ürün</div>#}
{#            <div class="col-md-3 col-sm-6" style="background-color: #244cff; height: 100px;">4. Ürün</div>#}
{#        </div>#}

{#        <div class="row">#}
{#            <div class="col-md-10" style="background-color: #ff101b; height: 100px;"></div>#}
{#            <div class="col-md-4" style="background-color: #5f5aff; height: 100px;"></div>#}
{#        </div>#}

        <div class="row">
            <div class="col-md-4" style="background-color: #ff101b; height: 100px;"></div>
            <div class="col-md-8" style="background-color: #5f5aff; height: 100px;">
                <div class="row">
                    <div class="col-md-2" style="background-color: #5cff00; height: 100px;"></div>
                    <div class="col-md-6" style="background-color: #ff00ef; height: 100px;"></div>
                    <div class="col-md-4" style="background-color: #3c2aff; height: 100px;"></div>
                </div>
            </div>
        </div>
    </div>
    Hoşgeldin, {{ request.user.username }}
{% endblock %}

django-dersleri-master/templates/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-success alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          {{ message }}
        </div>
    {% endfor %}
{% endif %}